name: Reusable workflow for AWS Lambda Deployment
on:
  workflow_call:
    inputs:
      GROUP_ID:
        required: true
        type: string
      ARTIFACT_ID:
        required: true
        type: string
      ARTIFACT_SHADED_JAR_CLASSIFIER:
        required: true
        type: string
      developmentVersion:
        required: true
        type: string
      AWS_LAMBDA_FUNCTION_NAME_LIST:	# List of lambda function-names to be deployed with the same artifact, space separated string list
        required: true
        type: string
      MVN_CACHE_ID:
        required: true
        type: string
      AWS_REGION:
        required: false
        type: string
    secrets:
      BUILD_USR:
        required: true
      BUILD_KEY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false
  
jobs:
  aws-deploy:
        
    runs-on: ubuntu-latest

    steps:
      - name: aws authentication
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ inputs.MVN_CACHE_ID }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ inputs.MVN_CACHE_ID }}-maven-

      - name: Download artifact by version referred in input
        run: |
          curl -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.BUILD_KEY }}" "https://raw.githubusercontent.com/RadascentCommon/rad-parent-pom/master/MavenSettings4GitHubCI_CD.xml" > ~/.m2/settings.xml
          sed -i 's/#{BUILD_ACTOR}#/${{ secrets.BUILD_USR }}/g' settings.xml
          sed -i 's/#{BUILD_TOKEN}#/${{ secrets.BUILD_KEY }}/g' settings.xml
          mvn dependency:get \
            -DremoteRepositories=https://maven.pkg.github.com/Radascent/maven-repos-external \
            -Dartifact=${{ inputs.GROUP_ID }}:${{ inputs.ARTIFACT_ID }}:${{ inputs.developmentVersion }}:jar:${{ inputs.ARTIFACT_SHADED_JAR_CLASSIFIER }} \
            -Dtransitive=false \
            -Ddest=${{ inputs.ARTIFACT_ID }}-shaded.jar \
            -s settings.xml

      - name: Lambda deployment
        run: |
          for function in ${{ inputs.AWS_LAMBDA_FUNCTION_NAME_LIST }}; \
          do aws lambda update-function-code --function-name $function --zip-file fileb://./${{ inputs.ARTIFACT_ID }}-shaded.jar; \
          done \
 