
name: Reusable workflow for Java CI with Maven; calls clean install deploy lifecycles.

on:
  workflow_call:
    inputs:
      GITHUB_ACTOR:
        required: true
        type: string
      GITHUB_TOKEN:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false
      AWS_REGION:
        required: false
  
jobs:
  mvn-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: mvn -B clean install deploy
